name: Build Go Binary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o docker-starter main.go

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create or Update GitHub Release and Upload Asset
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.SHORT_SHA }}
          name: Release ${{ steps.vars.outputs.SHORT_SHA }}
          body: Automaticky vygenerovaný release pro commit ${{ steps.vars.outputs.SHORT_SHA }}.
          artifacts: docker-starter
          allowUpdates: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}