name: Build Go Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o docker-starter main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-starter-linux-amd64
          path: docker-starter